
export const quotes: string[] = [
    "The secret of getting ahead is getting started.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The journey of a thousand miles begins with a single step.",
    "Don't watch the clock; do what it does. Keep going.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream big and dare to fail.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You are never too old to set another goal or to dream a new dream.",
    "Act as if what you do makes a difference. It does.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "If you want to lift yourself up, lift up someone else.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The way to get started is to quit talking and begin doing.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "If you can dream it, you can do it.",
    "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "All our dreams can come true, if we have the courage to pursue them.",
    "Don't be afraid to give up the good to go for the great.",
    "Things work out best for those who make the best of how things work out.",
    "If you want to achieve greatness stop asking for permission.",
    "I find that the harder I work, the more luck I seem to have.",
    "The secret of success is to do the common thing uncommonly well.",
    "Good, better, best. Never let it rest. 'Til your good is better and your better is best.",
    "To be successful, you must accept all challenges that come your way. You can't just accept the ones you like.",
    "The starting point of all achievement is desire.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
    "The only place where success comes before work is in the dictionary.",
    "Don't let what you cannot do interfere with what you can do.",
    "You don't have to be great to start, but you have to start to be great.",
    "There are no shortcuts to any place worth going.",
    "Success is not in what you have, but who you are.",
    "In order to succeed, we must first believe that we can.",
    "All progress takes place outside the comfort zone.",
    "You may be disappointed if you fail, but you are doomed if you don't try.",
    "The path to success is to take massive, determined action.",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
    "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
    "The successful warrior is the average man, with laser-like focus.",
    "You can't build a reputation on what you are going to do.",
    "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.",
    "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit.",
    "What seems to us as bitter trials are often blessings in disguise.",
    "The distance between insanity and genius is measured only by success.",
    "Don't be distracted by criticism. Remember--the only taste of success some people get is to take a bite out of you.",
    "I cannot give you the formula for success, but I can give you the formula for failure--which is: Try to please everybody.",
    "Success usually comes to those who are too busy to be looking for it.",
    "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.",
    "If at first you don't succeed, try, try again.",
    "The secret to success is to know something nobody else knows.",
    "I never dreamed about success. I worked for it.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Try not to become a man of success. Rather become a man of value.",
    "Never give in, never give in, never, never, never, never--in nothing, great or small, large or petty--never give in except to convictions of honor and good sense.",
    "Stop chasing the money and start chasing the passion.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Success is a lousy teacher. It seduces smart people into thinking they can't lose.",
    "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.",
    "The road to success is always under construction.",
    "If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.",
    "A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "If you have no critics, you'll likely have no success.",
    "What is success? I think it is a mixture of having a flair for the thing that you are doing; knowing that it is not enough, that you have got to have hard work and a certain sense of purpose.",
    "The ladder of success is best climbed by stepping on the rungs of opportunity.",
    "The size of your success is measured by the strength of your desire; the size of your dream; and how you handle disappointment along the way.",
    "Victory is sweetest when you've known defeat.",
    "Success is how high you bounce when you hit bottom.",
    "The best revenge is massive success.",
    "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.",
    "I'm a success today because I had a friend who believed in me and I didn't have the heart to let him down.",
    "Do not be embarrassed by your failures, learn from them and start again.",
    "Success is not just about making money. It's about making a difference.",
    "Ambition is the path to success. Persistence is the vehicle you arrive in.",
    "The master has failed more times than the beginner has even tried.",
    "The successful man will profit from his mistakes and try again in a different way.",
    "Perseverance is failing 19 times and succeeding the 20th.",
    "Just because you fail once doesn't mean you're gonna fail at everything.",
    "The secret of our success is that we never, never give up.",
    "Failure is the condiment that gives success its flavor.",
    "There is no success without hardship.",
    "Eighty percent of success is showing up.",
    "The key to success is to focus our conscious mind on things we desire not things we fear.",
    "Success is the child of audacity.",
    "Patience, persistence and perspiration make an unbeatable combination for success.",
    "Your positive action combined with positive thinking results in success.",
    "Success is not to be pursued; it is to be attracted by the person you become.",
    "One important key to success is self-confidence. An important key to self-confidence is preparation.",
    "Self-belief and hard work will always earn you success.",
    "Have a determination that is incorruptible.",
    "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.",
    "The key to being a successful person is to be a person of value.",
    "Success is a journey not a destination.",
    "Success depends upon previous preparation, and without such preparation there is sure to be failure.",
    "It is better to fail in originality than to succeed in imitation.",
    "Opportunities don't happen. You create them."
];
